version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install Terraform
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      # Initialize Terraform
      - terraform init

  build:
    commands:
      #
